version: '3'

services:
  blog:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./:/app/src
      - /app/src/node_modules
    command: yarn dev
    ports:
      - 3000:3000
    restart: always
