version: "3"

services:
  blog:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./client:/usr/src
      - /usr/src/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    restart: always
